version: 10.0.{build}
image: Visual Studio 2017
configuration: Release

install:
- ps: >-
    cd src

    dotnet tool install -g coveralls.net --version 1.0.0

    nuget restore Markdig.sln

    $env:MARKDIG_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")

    $env:MARKDIG_VERSION_SUFFIX = ""

    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:MARKDIG_VERSION_SUFFIX = ""
        }
    	  if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
           $env:MARKDIG_VERSION_SUFFIX = "pre$env:MARKDIG_BUILD_NUMBER"
        }
      }
    }

build:
  project: src/Markdig.sln
  verbosity: minimal

after_build: >
  dotnet SpecFileGen/bin/Release/netcoreapp2.2/SpecFileGen.dll

test_script:
- cmd: >-
    dotnet test Markdig.Tests -c Release --no-build

    dotnet test Markdig.Tests -c Debug

    dotnet test Markdig.Tests -c Release -f netcoreapp2.1 /p:CollectCoverage=true /p:Include=\"[Markdig]*\" /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../coverage.xml

after_test:
- ps: >-
    if($env:APPVEYOR_REPO_BRANCH -eq "master") {
      cd ..
      csmacnz.Coveralls --opencover -i coverage.xml
      cd src
    }

before_package:
- cmd: >-
    msbuild /t:pack /p:VersionSuffix="%MARKDIG_VERSION_SUFFIX%" /p:Configuration=Release Markdig/Markdig.csproj

    msbuild /t:pack /p:VersionSuffix="%MARKDIG_VERSION_SUFFIX%" /p:Configuration=Release Markdig.Signed/Markdig.Signed.csproj

artifacts:
- path: src\**\*.nupkg
  name: Markdig Nugets

deploy:
- provider: NuGet
  api_key:
    secure: 7cthHh+wYWZjhqxaxR6QObRaRnstvFkQOY7MkxIsC5kpQEBlKZXuinf0IybbYxJt
  on:
    appveyor_nuget_push: true